(deftheme rose-pine-color-c
  "All natural pine,  faux fur and a bit of soho vibes for the classy minimalist.")

(custom-theme-set-faces
 'rose-pine-color-c
 '(bold ((((class color) (min-colors 16777215)) (:foreground "#555169"))))
 '(italic ((((class color) (min-colors 16777215)) (:foreground "#cecaed"))))
 '(bold-italic ((((class color) (min-colors 16777215)) (:foreground "#555169"))))
 '(fixed-pitch-serif ((((class color) (min-colors 16777215)) (:foregrund "#555169"))))
 '(variable-pitch ((((class color) (min-colors 16777215)) (:foregroud "#555169"))))
 '(cursor ((((class color) (min-colors 16777215)) (:background "#e0def4"))))
 '(shadow ((((class color) (min-colors 16777215)) (:foreground "#cecaed"))))
 '(success ((t (:foreground "lawn green"))))
 '(warning ((((class color) (min-colors 16777215)) (:foreground "#eb6f92"))))
 '(error ((((class color) (min-colors 16777215)) (:foreground "#f6c177"))))
 '(match ((((class color) (min-colors 16777215)) (:foreground "#eb6f92"))))
 '(buffer-menu-buffer ((((class color) (min-colors 16777215)) (:foreground "#555169"))))
 '(minibuffer-prompt ((((class color) (min-colors 16777215)) (:foreground "#555169"))))
 '(link ((((class color) (min-colors 16777215)) (:foreground "#c4a7e7"))))
 '(fringe ((((class color) (min-colors 16777215)) (:foreground "#cecaed"))))
 '(isearch ((((class color) (min-colors 16777215)) (:foreground "#555169"))))
 '(isearch-fail ((((class color) (min-colors 16777215)) (:foreground "#cecaed"))))
 '(lazy-highlight ((((class color) (min-colors 16777215)) (:foreground "#6e6a86"))))
 '(trailing-whitespace ((((class color) (min-colors 16777215)) (:foreground "#6e6a86"))))
 '(show-paren-match ((((class color) (min-colors 16777215)) (:foreground "#eb6f92"))))
 '(tooltip ((((class color) (min-colors 16777215)) (:height 0.85))))
 '(secondary-selection ((t (:foreground "#6e6a86"))))
 '(completions-common-part ((((class color) (min-colors 16777215)) (:foreground "#cecaed"))))
 '(completions-first-difference ((((class color) (min-colors 16777215)) (:foreground "#eb6f92"))))
 '(font-lock-comment-face ((t (:foreground "burlywood"))))
 '(font-lock-doc-face ((((class color) (min-colors 16777215)) (:foreground "#cecaed"))))
 '(font-lock-string-face ((t (:foreground "#FFAF87"))))
 '(font-lock-constant-face ((((class color) (min-colors 16777215)) (:foreground "#c4a7e7"))))
 '(font-lock-warning-face ((((class color) (min-colors 16777215)) (:foreground "#eb6f92"))))
 '(font-lock-function-name-face ((t (:foreground "hot pink"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 16777215)) (:foreground "#555169"))))
 '(font-lock-builtin-face ((((class color) (min-colors 16777215)) (:foreground "#c4a7e7"))))
 '(font-lock-type-face ((((class color) (min-colors 16777215)) (:foreground "#c4a7e7"))))
 '(font-lock-keyword-face ((t (:foreground "#AFD7D7" :width expanded))))
 '(tree-sitter-hl-face:function\.call ((t (:foreground "#FFAFAF" :underline nil))))
 '(tree-sitter-hl-face:function ((t (:foreground "#FFAFAF" :inherit font-lock-function-name-face))))
 '(lsp-face-semhl-type ((t (:inherit font-lock-type-face :foreground "cyan2"))))
 '(ivy-subdir ((t (:inherit (dired-directory)))))
 '(xref-file-header ((t (:foreground "#FFAF87"))))
 '(default ((t (:background "black" :foreground "white"))))
 '(markdown-header-face ((t (:foreground "#FFAF87")))))

(provide-theme 'rose-pine-color-c)
